[group]AY_PR
[note]wordwrap
以下、少々補足です。

■パラメータ関連
最大値は、表示上９９９ですが、実際は7FFFFFFF(h)までよいようです。（いらん）

■ＣＧ関連
更新は各ＥＮＤ開始時のみなので、フラグを書き換えても、なんらかのＥＮＤを見ないとファイルに反映されません。インストフォルダ内[ayanami.ini]の記述を、ALBUM1=-134215681／ALBUM2=-134215681／ALBUM3=-134215681と書き換えてもＯＫ。

■おまけ
着せ替えレイちゃん：
任意の服装を選択した後、更新作業が必要です。一旦、街に移動してから戻るとか、スケジュールを実行するとか。シナリオ中強制着せ替えする部分には無効。

付記：
各ＥＮＤの決定要因は、１）好感度の高い相手２）実行数最多コマンド３）綾波の状態等のようです。
[/note]

[subject]パラメータ関連:dir
	[subject]所持金/現在値/固定:calc,0xD70A20,0x00,0x05F5E09C,unsigned
	[repeat]AYLST->AYREP1,0,11,1
[/group]


[group]AY_F1
[e_with],0x0000,0x03E7,unsigned
[subject]主人公への好感度/現在値/固定:calc,_[:0x47EB54:]-0x10
[subject]シンジへの好感度/現在値/固定:calc,_[:0x47EB54:]-0x250
[subject]ゲンドウへの好感度/現在値/固定:calc,_[:0x47EB54:]-0x280
[/e_with]
[/group]


[group]AY_CG
[subject]ＡＬＢＵＭ:dir
	[subject]ＡＬＬ ＯＮ/実行/_:toggle,0x485F58,0x485F60-FF0700F8
	[subject]ＡＬＬ ＯＦＦ/実行/_:toggle,0x485F58,0x485F60-00000000
[/group]


[group]AY_EX
[subject]着せ替えレイちゃん（爆）:dir
	[subject]服装変更/_:list,0x47A064,AYLST->LST_b,0x01,0x01
[/group]


[group]AYREP1
[subject][! @AYLST->LST_a,$Val !]/現在値/固定:calc,_[:0x47EB54:]-0x[! $Val*0x30 !]+0x200,0x0000,0x03E7,unsigned
[/group]


[group]LST_a
肉体強度
知能指数
精神防壁
ＰＨ分泌
基本語彙
社会適応
道徳感覚
感受能力
疲労係数
シンクロ率
ＡＴフィールド
[/group]


[group]LST_b
制服
プラグスーツ
患者服
体操服（ブルマ）
スクール水着
水着（白）
弓道服
レオタード
浴衣
ナイトドレス
晴れ着
水着（ビキニ）
白雪姫衣装
魔女衣装
木(^^;
体操服（ジャージ）
フリルのドレス
リボンのドレス
キャミソール
サマーセータ－
スパッツ
キャミとパンツ
ビスチェ
チャイナドレス
猫耳
うさぐるみ
[/group]