[group]GHT_SSG
[note]wordwrap
‘Š•Ï‚í‚ç‚¸‚ƒŒƒxƒ‹‚Èo—ˆ‰h‚¦‚Å‚·‚ªc‚QlƒvƒŒƒCŽž‚Ì‚b‚o‚t‚ªŒÜŒŽ”ˆ‚¢‚—
[/note]

[subject]–³“G‰»/ŽÀs/_:toggle,0x4310B7,E91B02000090,0F841A020000
[subject]ƒI[ƒo[ƒq[ƒgƒQ[ƒW‘‚¦‚È‚¢/ŽÀs/_:toggle,0x43255B,3ED8650C9090,D881D4000000
[subject]”ƒ‚¢•¨–³—¿‰»/ŽÀs/_:toggle,0x45B71E,8B6D0833C08904ADBC0360005DC3,5DC3CCCCCCCCCCCCCCCCCCCCCCCC
[subject]ˆÚ“®‘¬‚S”{‰»/ŽÀs/_:toggle,0x433578,EB00????????????????230E41,7412????????????????E87D59
[subject]UŒ‚—Í‚P‚Q”{‰»/ŽÀs/_:b_toggle,0x00,GHTLST->GHT_a,offset

[/group]


[group]GHT_a
0x431722,EB00,7423
0x43173E,D34D42,E87D59
[/group]
