[group]KR_PR
[note]wordwrap
うちのＰＣだとデバッガを用いた解析はちとキツイです。いい加減スペック上げないとダメかなぁ(^^;　あぁ、シナリオの方はいい感じです。主人公が子持ちってシチュがホワイトアルバム以来の新鮮さで。あとは、さくらの「うにゃ～♪」ですか。あれは破壊力抜群です(^^;

好感度：
上下限は常識的な範囲で設定したものです。

ＣＧモード関連：
ＣＧの方は、シナリオ中に機能を実行し任意のＣＧを見ればＡＬＬ化しますが、後日談や回想の方は回想モードに入ってから利用する一時仕様のものです。これもやり方次第では
ＡＬＬ化できますが、前記の如く解析環境が不安定なので見送りました。自分でやりたい方のために方法を記すと、

１）シナリオ中である状態を示すフラグをサーチしておく
２）タイトル画面等に戻る際実行されるセーブデータからのデータ復帰処理を解析する
３）１）のフラグが起ってる場合、２）の処理をキャンセルする内容のパラサイトルーチンを設置

これでＣＧのように、シナリオ中にＨリプレイＡＬＬ化を実行した後任意のシーンを見ればＡＬＬ化されるかと。そのうち、自分でやるかもしれませんが。
[/note]

[subject]パラメータ関連:dir
 [subject]好感度確認調整:dir
	 [repeat]KRLST->KRREP1,0,4,1
[root]

[subject]ＣＧモード関連:dir
	[replace]_[:(MName::SYSTEM.UNT)+0x334CC:],KRLST->KR_CG
[root]

[/group]


[group]KRREP1
[subject][! @KRLST->LST_a,$Val !]/現在値/_:calc,_[:(MName::SYSTEM.UNT)+0x334CC:]+0xD80+0x[! 0x04*$Val !],0x320,0x4B0,unsigned
[/group]


[group]LST_a
雪桜姫乃
綾瀬紫苑
雪桜伊吹
真崎楓
[/group]


[group]KR_CG
[subject]ＣＧモード:dir
	[subject]ＡＬＬ ＯＮ/実行/_:toggle,0x5DC,0x67F-01
	[subject]ＡＬＬ ＯＦＦ/実行/_:toggle,0x5DC,0x67F-00
[back]
[subject]Ｈリプレイ:dir
	[subject]ＡＬＬ ＯＮ/実行/_:toggle,0x780,0x796-01
	[subject]ＡＬＬ ＯＦＦ/実行/_:toggle,0x780,0x796-00
[back]
[subject]クリアフラグ:dir
	[subject]ＡＬＬ ＯＮ/実行/_:toggle,0x76C,0x770-01
	[subject]ＡＬＬ ＯＦＦ/実行/_:toggle,0x76C,0x770-00
[/group]
