[group]SRV_MA
[note]wordwrap
…いろんな意味でヤバイんじゃないの？（笑）

以下、少々補足です。

デバッグモード：
機能を実行した後、シナリオ内で右クリックして下さい。タイトルバーのタイトル名が『Ｓｎｏｗ・ラディッシュ・バケーション！！』から『スノラディ－デバッグ－』に変更されれば成功。環境設定内にデバッグタブが出現します。またこのままでは、ポップアップメニューが呼び出せないので、デバッグ実行後は機能を外して下さい。１度出現すれば、当該起動中はデバッグメニューを永続使用できます。

パラメータ関連：
一定値以上且つ、ヒロインの居場所と止イベント場所が一致すると…。

神楽眠さ：
０にしておけば、眠くならずフルタイムで動けます。

制服タイプ変更：
…だから、ヤバイんじゃないのコレ？（笑）


＊オーバーフロー・スタックソフトウェアのデバッグ解析は既にKEIさんが行っておりますが、KEIさんの解析と、当方のものは必要なアプローチが異なるものです。解析者の礼としてKEIさんにはこちらの解析プロセスを公開したうえで、公表に関する了承を頂いています。
[/note]

[subject]環境関連:dir
	[subject]デバッグモード/実行/_:b_toggle,0x423B4F,SRVLST->SRV_a,real
[/group]


[group]SRV_PR
[subject]感情値確認調整:dir
	[repeat]SRVLST->SRVREP1,0,7,1
[back]
[subject]神楽眠さ/現在値/固定:calc,_[:0x478998:]+0xC420,0x00,0x18,unsigned
[/group]


[group]SRV_F1
[subject]制服タイプ任意変更/_:list,_[:0x478998:]+0xC4CC,SRVLST->LST_e,0x00,0x01
[subject]居場所確認調整:dir
	[repeat]SRVLST->SRVREP2,0,6,1
	[subject]止イベント/_:d_list,_[:0x478998:]+0xC4C8,SRVLST->LST_c,0x00,0x0a,SRVLST->LST_d,offset
[/group]


[group]SRVREP1
[subject][! @SRVLST->LST_a,$Val !]/現在値/固定:calc,_[:0x478998:]+0x[! 0xC4B0+$Val*4 !],0x00,0xFF,unsigned
[/group]


[group]SRVREP2
[subject][! @SRVLST->LST_b,$Val !]/_:d_list,_[:0x478998:]+0x[! 0xC3B4+$Val*4 !],SRVLST->LST_c,0x00,0x0a,SRVLST->LST_d,offset
[/group]


[group]LST_a
神楽
止
萌葱
浅葱
巴
ありす
初花
[/group]


[group]LST_b
萌葱
ありす
浅葱
巴
初花
止
[/group]


[group]LST_c
不在
止の部屋
浅葱と巴の部屋
踊り場
玄関
寝室
リビング
露天風呂
倉庫
スノーラディッシュ
店の外
[/group]


[group]LST_d
,0x00=0000
,0x00=0100
,0x00=0200
,0x00=0300
,0x00=0400
,0x00=0500
,0x00=0600
,0x00=0700
,0x00=0800
,0x00=0900
,0x00=0A00
[/group]


[group]LST_e
ジェイド
アンバー
ナース
[/group]


[group]SRV_a
0x423B4F,EB
0x4249EA,03,02
0x43908F,EB00
0x439102,EB00
0xBE68E0,01
[/group]