[group]TMD_SSG
[note]wordwrap
※ver1.40で確認。以外のverには基本的に対応できません（例外も有ります）。

※SpoilerALのプロセス検出仕様により、Window2000上ではプロセス検出に失敗します。

http://onionimu.hp.infoseek.co.jp/usr/redcat/204/01.html　以下、

Ｑ／一部タイトルが、ガイドフォームに「プロセスの展開に失敗しました」と表示されて正常動作しません。

を参考に解決してください。

※「スロット」は隊列左上を１とし右に向かって１～３、下段が４～６になります。空きスロットへのTC極小化も有効になってしまいますのでご注意を。

※数値の多くが基本値（固定値）をもっているため、ＬＶＵＰや拠点効果で戻る場合があります。

※現時点で、こちらは序盤（斉藤撃破時）です。それ以降の参考情報が無いと対応が不可・不安定な状況にはSSGが対応していないケースもあります。こちらのプレイに沿って追加・修正する予定です。

[/note]

[subject]ver1.32／1.33:dir

[subject]戦闘関連:dir
 [subject]戦闘時HP維持/固定:d_toggle,_[:[:[:[:0x4DDA24:]+0x04:]+0x48:]+0x1604:],TMDLST->LST_a,TMDLST->LST_b,offset
 [subject]戦闘時MPMIN化/固定:d_toggle,_[:[:[:[:0x4DDA24:]+0x04:]+0x48:]+0x1614:],TMDLST->LST_a,TMDLST->LST_c,offset
 [subject]戦闘時TC極小化/固定:d_toggle,_[:[:[:[:0x4DDA24:]+0x04:]+0x48:]+0x1624:],TMDLST->LST_a,TMDLST->LST_d,offset
 [subject]スペルカード使用回数極大化/固定:d_toggle,_[:[:[:[:0x4DDA24:]+0x04:]+0x48:]+0x0FB4:],TMDLST->LST_a,TMDLST->LST_e,offset
[back]
[subject]隊列データ:dir
 [repeat]TMDLST->TMDREP1,1,7,1
[back]
[subject]基本データ:dir
 [replace]_[:[:[:0x4DDA24:]+0x04:]+0x04:],TMDLST->TMD_a
[back]

[back]

[subject]ver1.40:dir

[subject]戦闘関連:dir
 [subject]戦闘時HP維持/固定:d_toggle,_[:[:[:[:0x4DFB44:]+0x04:]+0x48:]+0x1604:],TMDLST->LST_a,TMDLST->LST_2b,offset
 [subject]戦闘時MPMIN化/固定:d_toggle,_[:[:[:[:0x4DFB44:]+0x04:]+0x48:]+0x1614:],TMDLST->LST_a,TMDLST->LST_c,offset
 [subject]戦闘時TC極小化/固定:d_toggle,_[:[:[:[:0x4DFB44:]+0x04:]+0x48:]+0x1624:],TMDLST->LST_a,TMDLST->LST_d,offset
 [subject]スペルカード使用回数極大化/固定:d_toggle,_[:[:[:[:0x4DFB44:]+0x04:]+0x48:]+0x0FB4:],TMDLST->LST_a,TMDLST->LST_e,offset
[back]
[subject]隊列データ:dir
 [repeat]TMDLST->TMDREP2,1,7,1
[back]
[subject]基本データ:dir
 [replace]_[:[:[:0x4DFB44:]+0x04:]+0x04:],TMDLST->TMD_a
[back]

[back]

[/group]


[group]TMDREP1
[subject]_mem,_[\:[\:[\:[\:0x4DDA24\:]+0x04\:]+0x48\:]+0x0654\:]+0x[!0x04*$Val!],4,list,<Empty>,TMDLST->LST_z,0,1:dir
 [subject]EXP/現在値/_:calc,_[:[:[:[:0x4DDA24:]+0x04:]+0x48:]+0x0804:]+0x[!0x04*$Val!],0x000000,0x98967F,unsigned
 [subject]MAXHP/現在値/固定:calc,_[:[:[:[:0x4DDA24:]+0x04:]+0x48:]+0x07F4:]+0x[!0x04*$Val!],0x000000,0x01869F,unsigned
[back]
[/group]


[group]TMDREP2
[subject]_mem,_[\:[\:[\:[\:0x4DFB44\:]+0x04\:]+0x48\:]+0x0654\:]+0x[!0x04*$Val!],4,list,<Empty>,TMDLST->LST_z,0,1:dir
 [subject]EXP/現在値/_:calc,_[:[:[:[:0x4DFB44:]+0x04:]+0x48:]+0x0804:]+0x[!0x04*$Val!],0x000000,0x98967F,unsigned
 [subject]MAXHP/現在値/固定:calc,_[:[:[:[:0x4DFB44:]+0x04:]+0x48:]+0x07F4:]+0x[!0x04*$Val!],0x000000,0x01869F,unsigned
[back]
[/group]


[group]TMD_a
[e_with],0x000000,0x05F5E0FF,unsigned
 [subject]所持金/現在値/_:calc,0xD4
 [subject]プレイ時間/現在値/_:calc,0xD8
 [subject]戦闘回数/現在値/_:calc,0xDC
 [subject]総殺戮数/現在値/_:calc,0xE0
[/e_with]
[/group]


[group]TMD_c
[e_with],0x000000,0x05F5E0FF,unsigned
 [subject]1/現在値/_:calc,0x04
 [subject]2/現在値/_:calc,0x08
 [subject]3/現在値/_:calc,0x0C
 [subject]4/現在値/_:calc,0x10
 [subject]5/現在値/_:calc,0x14
 [subject]6/現在値/_:calc,0x18
 [subject]7/現在値/_:calc,0x1C
 [subject]8/現在値/_:calc,0x20
 [subject]9/現在値/_:calc,0x24
 [subject]10/現在値/_:calc,0x28
[/e_with]
[/group]


[group]LST_a
スロット１
スロット２
スロット３
スロット４
スロット５
スロット６
[/group]


[group]LST_b
0x04=$4 [:[:[:[:[:0x4DDA24:]+0x04:]+0x48:]+0x07F4:]+0x04:] $$/??
0x08=$4 [:[:[:[:[:0x4DDA24:]+0x04:]+0x48:]+0x07F4:]+0x08:] $$/??
0x0C=$4 [:[:[:[:[:0x4DDA24:]+0x04:]+0x48:]+0x07F4:]+0x0C:] $$/??
0x10=$4 [:[:[:[:[:0x4DDA24:]+0x04:]+0x48:]+0x07F4:]+0x10:] $$/??
0x14=$4 [:[:[:[:[:0x4DDA24:]+0x04:]+0x48:]+0x07F4:]+0x14:] $$/??
0x18=$4 [:[:[:[:[:0x4DDA24:]+0x04:]+0x48:]+0x07F4:]+0x18:] $$/??
[/group]


[group]LST_2b
0x04=$4 [:[:[:[:[:0x4DFB44:]+0x04:]+0x48:]+0x07F4:]+0x04:] $$/??
0x08=$4 [:[:[:[:[:0x4DFB44:]+0x04:]+0x48:]+0x07F4:]+0x08:] $$/??
0x0C=$4 [:[:[:[:[:0x4DFB44:]+0x04:]+0x48:]+0x07F4:]+0x0C:] $$/??
0x10=$4 [:[:[:[:[:0x4DFB44:]+0x04:]+0x48:]+0x07F4:]+0x10:] $$/??
0x14=$4 [:[:[:[:[:0x4DFB44:]+0x04:]+0x48:]+0x07F4:]+0x14:] $$/??
0x18=$4 [:[:[:[:[:0x4DFB44:]+0x04:]+0x48:]+0x07F4:]+0x18:] $$/??
[/group]


[group]LST_c
0x04=00000000/??
0x08=00000000/??
0x0C=00000000/??
0x10=00000000/??
0x14=00000000/??
0x18=00000000/??
[/group]


[group]LST_d
0x04=*{????FFFF::????????::01000000*}/??
0x08=*{????FFFF::????????::01000000*}/??
0x0C=*{????FFFF::????????::01000000*}/??
0x10=*{????FFFF::????????::01000000*}/??
0x14=*{????FFFF::????????::01000000*}/??
0x18=*{????FFFF::????????::01000000*}/??
[/group]


[group]LST_e
0x04=63000000630000006300000063000000630000006300000063000000630000006300000063000000/??
0x54=63000000630000006300000063000000630000006300000063000000630000006300000063000000/??
0xA4=63000000630000006300000063000000630000006300000063000000630000006300000063000000/??
0xF4=63000000630000006300000063000000630000006300000063000000630000006300000063000000/??
0x0144=63000000630000006300000063000000630000006300000063000000630000006300000063000000/??
0x0194=63000000630000006300000063000000630000006300000063000000630000006300000063000000/??
[/group]


[group]LST_z
--------
霊夢
魔理沙
妖夢
咲夜
ルーミア
チルノ
中国
パチュリー
レミリア
フランドール
レティ
橙
藍
紫
アリス
ルナサ
メルラン
リリカ
幽々子
リグル
ミスティア
慧音
慧音
うどんげ
てゐ
永琳
輝夜
妹紅
大妖精
小悪魔
斉藤
斉藤
斉藤
斉藤
スピアード
南森
村田
デビル
ヴァンサズ
ライザーグ
ザルマン
ナチ
ハインリッヒ
シュタイナー
フレイザード
--------
ホチキス
クルップ
--------
--------
久瀬
南
ミズカ
髭
おやぢ
高槻
アヴェスタ
サイヤ
川口さん
綱
坂田
--------
文
小町
ザナドゥ
メディスン
幽香
魅魔
魔梨沙
--------
斉藤
霖之助
レミリア
うどんげ
ヲタパチュ
[/group]
