[group]TY2_CG
[note]wordwrap
セーブデータからの配列復元が頻繁なため、セーブデータと同じにＡＬＬ化させる方法を採ります。

１）任意のデータから再開、或いは始めからプレイスタート

２）ＳＳＧでＡＬＬ化させたい項目にチェックを入れる

３）任意のスロットにデータを保存（状態は問はず）
[/note]

[subject]ＣＧモード関連:dir
	[subject]ＳＰＥＣＩＡＬ:dir
		[subject]ＡＬＬ化項目選択/_:d_toggle,_[:0x470B60:]+0x1F86C,TY2LST->LST_a,TY2LST->LST_b,offset
	[back]
[/group]


[group]LST_a
ＣＧ鑑賞
音楽鑑賞
Ｈシーン鑑賞
エンディング再生
[/group]


[group]LST_b
0x7D1=0x98F-01/??
0x5DD=0x5F7-01/??
0x578=0x582-01/??
0x514=0x52D-01/??
[/group]
