[group]WK_MA
[note]wordwrap
再び和製テーブルトークタイプのＲＰＧをプレイできたのは嬉しかったですね。地味ですが、かなりやり込めます。７月～８月は色々発売ラッシュになりましたが、１番お勧めかもしれないです。

以下、少々補足です。

■■環境関連
ウインドウモード起動：
本作はフルスクリーン固定＋[ALT+TAB]に若干制限がかかるので、ウインドウモードプレイの方が快適です。ただし、かなりシビアなタイミングの関係上、成功率が高くありません(^^;　更新周期を最速の"1"にして複数回試行し、うまくいったら、負担を減らすためにも周期は戻すようにして下さい。

■■ＲＰＧパート関連
スキル上げ放題：
現在値以上の必要値になっても、そのまま上昇させることができ、且つ実行時の消費経験値を０にします。

スキルＬＶ制限解除：
基本スキルのＬＶ３０制限を解除。ただし、上昇制限が無くなるので、上げ過ぎによる不都合に御注意。

経験値：
反映させるためには、一旦ページ切り替え等を行う必要があります。

自動回復カスタム化：
自動回復が発生しない幾つかの場面でも回復ができ、且つ味方は１回の回復で全快する機能。

味方行動待機カウントスキップ化：
各工作行動や戦闘行動に掛かる独自の発生ウエイトをスキップ。矢継ぎ早な行動が可能です。
[/note]

[subject]環境関連:dir
	[subject]ウインドウモード起動/実行/固定:toggle,0x425C8C,EB0490909090,0F85AD000000
[/group]


[group]WK_MA2
[subject]スキル上げ放題/実行/_:b_toggle,0x40F97F,WKLST->WK_b,real
[subject]スキルＬＶ制限解除/実行/_:toggle,0x4103F0,EB0490909090,0F8D8D000000
[subject]経験値/現在値/_:calc,0x5C4490,0x00000000,0x6FFFFFFF,unsigned
[subject]買い物で所持金減らない/実行/_:b_toggle,0x42C704,WKLST->WK_e,real
[subject]満腹度減らない/実行/_:b_toggle,0x42DA5B,WKLST->WK_a,real
[subject]自動回復カスタム化/実行/_:b_toggle,0x40A333,WKLST->WK_c,real
[subject]味方行動待機カウントスキップ化/実行/_:b_toggle,0x4049A7,WKLST->WK_d,real
[/group]


[group]WK_a
0x42DA5B,EB0190,FF480C
0x42DA66,EB0190,FF480C
[/group]


[group]WK_b
0x40F97F,B00190,0F9EC0
0x40FA0B,EB00,2BD1
[/group]


[group]WK_c
0x40A333,EB00,744D
0x40A341,EB00,753F
0x40A34B,EB,74
0x40A371,E9BDA0030090,8B54241003C2
0x444433,8B542410,00000000
0x444437,81F932255C00,000000000000
0x44443D,7D03,0000
0x44443F,8B5104,000000
0x444442,03C2,0000
0x444444,E92E5FFCFF90,000000000000
[/group]


[group]WK_d
0x4049A7,EB0D9090,66FF4004
0x4049B6,E995FA0300,9090909090
0x444450,3D52CC4400,0000000000
0x444455,7D08,0000
0x444457,66C74004FF7F,000000000000
0x44445D,EB04,0000
0x44445F,66FF4004,00000000
0x444463,E94305FCFF90,000000000000
[/group]


[group]WK_e
0x42C706,EB,79
0x42C727,EB029090,66295004
[/group]


[group]WKREP1
[subject][! L($Val+0x01) !]人目:dir
	[replace]_0x5BE5D8+0x[! 0xFC8*$Val !],WKLST->WK_PR
[/group]


[group]LST_a
男性
女性
[/group]


[group]WK_PR
[subject]名前/_:string,0x01,0x0C,null
[subject]姓名/_:string,0x1A,0x0C,null
[subject]性別/_:list,0x44,WKLST->LST_a,0x00,0x01
[subject]年齢/_:calc,0x45,0x10,0x18,unsigned
[e_with],0x000000,0x01869F,unsigned
[subject]最大体力/現在値/固定:calc,0x38
[subject]現在体力/現在値/固定:calc,0x34
[subject]空腹度/現在値/固定:calc,0x40
[subject]剣術スキル/現在値/固定:calc,0xF98
[subject]射術スキル/現在値/固定:calc,0xF9C
[subject]錬金術スキル/現在値/固定:calc,0xFA0
[subject]医療術スキル/現在値/固定:calc,0xFA4
[subject]計測術スキル/現在値/固定:calc,0xFA8
[subject]工作術スキル/現在値/固定:calc,0xFAC
[/e_with]
[back]
[/group]
