[group]YU_SSG
[note]wordwrap
一部の起動中のアドレス変動に未対応なため暫定版です。起動時を基準に環境差には対応できますので、
仮に変動するような場合、一旦プレイを終了し、再度起動しなおせば戻ります。変動といっても、今回
掲載されているデータ群に対してはそれほど頻繁なものでも無いですが。

[/note]

[subject]ＳＬＧパート関連:dir
	[replace]_[:0x40B38C:],YULST->YU_SLG
[root]

[subject]パラメータ関連:dir
	[replace]_[:0x40B38C:],YULST->YU_PR
[root]

[subject]ＣＧモード関連:dir
	[replace]_[:0x40B38C:],YULST->YU_CG
[root]

[/group]


[group]YU_SLG
[subject]存在フラグ任意編集/_:d_toggle,0x00,YULST->F1,YULST->F2,offset
[subject]調教予約状態任意編集/固定:d_list,0x600,YULST->CH_a,0x00,0x09,YULST->CH_b,offset
[subject]ＤＤＳ個数ＭＡＸ化/実行/固定:toggle,0x8C0,09000000
[subject]戦闘時敵攻撃力ＭＩＮ化/実行/_:toggle,0x1600,01000000
[subject]戦闘時敵素早さＭＩＮ化/実行/_:toggle,0x1630,01000000
[subject]戦闘時敵ＨＰＭＩＮ化/実行/_:toggle,0x1620,01000000
[/group]


[group]F1
赤木ゆり
相川茉莉子
木葉メイ
姉小路ありさ
なぎさ
[/group]


[group]F2
0x150=01000000/00000000
0x170=01000000/00000000
0x190=01000000/00000000
0x1C0=01000000/00000000
0x1D0=01000000/00000000
[/group]


[group]YU_PR
[subject]赤木ゆり:dir
	[replace]0x00,YULST->YU_PRya
[subject]相川茉莉子:dir
	[replace]0x00,YULST->YU_PRma
[subject]木葉メイ:dir
	[replace]0x00,YULST->YU_PRmk
[subject]姉小路ありさ:dir
	[replace]0x00,YULST->YU_PRaa
[subject]なぎさ:dir
	[replace]0x00,YULST->YU_PRnr
[/group]


[group]YU_PRaa
[subject]一般ステータス編集:dir
[subject]魂/現在値/固定:calc,0x220,0x0000,0x270F,unsigned
[subject]ＬＶ/現在値/固定:calc,0xEA0,0x00,0x09,unsigned
[e_with],0x0000,0x03E7,unsigned
[subject]生命/現在値/固定:calc,0xEC0
[subject]物攻/現在値/固定:calc,0xED0
[subject]ＣＬ攻/現在値/固定:calc,0xEE0
[subject]物防/現在値/固定:calc,0xEF0
[subject]ＣＬ防/現在値/固定:calc,0xF00
[subject]経験/現在値/固定:calc,0xF10
[subject]判断/現在値/固定:calc,0xF20
[/e_with]
[subject]召喚/現在値/固定:calc,0xF30,0x00,0x63,unsigned
[subject]特防/現在値/固定:calc,0xF40,0x00,0x63,unsigned
[e_with],0x0000,0x03E7,unsigned
[subject]感情/現在値/固定:calc,0xF50
[subject]知能/現在値/固定:calc,0xF60
[subject]性感/現在値/固定:calc,0xF70
[subject]従属/現在値/固定:calc,0x130
[/e_with]
[back]
[subject]武装任意変更:dir
[subject]近接装/_:list,0x560,YULST->YU_aa2,0x00,0x01
[subject]遠距離/_:list,0x570,YULST->YU_aa3,0x00,0x01
[subject]防御装/_:list,0x590,YULST->YU_aa4,0x00,0x01
[subject]補助装/_:d_list,0x580,YULST->YU_aa5,0x00,0x05,YULST->YU_aa6,offset
[back]
[subject]全スキルＭＡＸ化/実行/_:b_toggle,0x00,YULST->YU_aa1,offset
[back]
[/group]


[group]YU_PRnr
[subject]一般ステータス編集:dir
[subject]魂/現在値/固定:calc,0x1020,0x0000,0x270F,unsigned
[subject]ＬＶ/現在値/固定:calc,0xF80,0x00,0x09,unsigned
[e_with],0x0000,0x03E7,unsigned
[subject]生命/現在値/固定:calc,0xF90
[subject]物攻/現在値/固定:calc,0xFA0
[subject]ＣＬ攻/現在値/固定:calc,0xFB0 
[subject]物防/現在値/固定:calc,0xFC0
[subject]ＣＬ防/現在値/固定:calc,0xFD0
[subject]経験/現在値/固定:calc,0xFE0
[subject]判断/現在値/固定:calc,0xFF0
[/e_with]
[subject]召喚/現在値/固定:calc,0x1000,0x00,0x63,unsigned
[subject]特防/現在値/固定:calc,0x1010,0x00,0x63,unsigned
[e_with],0x0000,0x03E7,unsigned
[subject]感情/現在値/固定:calc,0x1030
[subject]知能/現在値/固定:calc,0x1040
[subject]性感/現在値/固定:calc,0x1050
[subject]従属/現在値/固定:calc,0x1060
[/e_with]
[back]
[subject]武装任意変更:dir
[subject]近接装/_:list,0x5A0,YULST->YU_nr2,0x00,0x01
[subject]遠距離/_:list,0x5B0,YULST->YU_nr3,0x00,0x01
[subject]防御装/_:list,0x8B0,YULST->YU_aa4,0x00,0x01
[subject]補助装/_:d_list,0x8A0,YULST->YU_nr4,0x00,0x05,YULST->YU_nr5,offset
[back]
[back]
[/group]


[group]YU_PRya
[subject]一般ステータス編集:dir
[subject]魂/現在値/固定:calc,0xCC0,0x0000,0x270F,unsigned
[subject]ＬＶ/現在値/固定:calc,0xC10,0x00,0x09,unsigned
[e_with],0x0000,0x03E7,unsigned
[subject]生命/現在値/固定:calc,0xC30
[subject]物攻/現在値/固定:calc,0xC40
[subject]ＣＬ攻/現在値/固定:calc,0xC50 
[subject]物防/現在値/固定:calc,0xC60
[subject]ＣＬ防/現在値/固定:calc,0xC70
[subject]経験/現在値/固定:calc,0xC80
[subject]判断/現在値/固定:calc,0xC90
[/e_with]
[subject]召喚/現在値/固定:calc,0xCA0,0x00,0x63,unsigned
[subject]特防/現在値/固定:calc,0xCB0,0x00,0x63,unsigned
[e_with],0x0000,0x03E7,unsigned
[subject]感情/現在値/固定:calc,0xCD0
[subject]知能/現在値/固定:calc,0xCE0
[subject]性感/現在値/固定:calc,0xCF0
[subject]従属/現在値/固定:calc,0x210
[/e_with]
[back]
[subject]武装任意変更:dir
[subject]近接装/_:list,0x300,YULST->YU_ya2,0x00,0x01
[subject]遠距離/_:list,0x880,YULST->YU_ya3,0x00,0x01
[subject]防御装/_:list,0x2D0,YULST->YU_aa4,0x00,0x01
[subject]補助装/_:d_list,0x890,YULST->YU_ya4,0x00,0x05,YULST->YU_aa6,offset
[back]
[subject]全スキルＭＡＸ化/実行/_:b_toggle,0x00,YULST->YU_ya1,offset
[back]
[/group]


[group]YU_PRma
[subject]一般ステータス編集:dir
[subject]魂/現在値/固定:calc,0xD70,0x0000,0x270F,unsigned
[subject]ＬＶ/現在値/固定:calc,0x220,0x00,0x09,unsigned
[e_with],0x0000,0x03E7,unsigned
[subject]生命/現在値/固定:calc,0x7D0
[subject]物攻/現在値/固定:calc,0x240
[subject]ＣＬ攻/現在値/固定:calc,0xD00
[subject]物防/現在値/固定:calc,0xD10
[subject]ＣＬ防/現在値/固定:calc,0xD20
[subject]経験/現在値/固定:calc,0xD30
[subject]判断/現在値/固定:calc,0xD40
[/e_with]
[subject]召喚/現在値/固定:calc,0xD50,0x00,0x63,unsigned
[subject]特防/現在値/固定:calc,0xD60,0x00,0x63,unsigned
[e_with],0x0000,0x03E7,unsigned
[subject]感情/現在値/固定:calc,0xD80
[subject]知能/現在値/固定:calc,0xD90
[subject]性感/現在値/固定:calc,0xDA0
[subject]従属/現在値/固定:calc,0xDB0
[/e_with]
[back]
[subject]武装任意変更:dir
[subject]近接装/_:list,0x2C0,YULST->YU_ma1,0x00,0x01
[subject]遠距離/_:list,0x2B0,YULST->YU_ma2,0x00,0x01
[subject]防御装/_:list,0x290,YULST->YU_aa4,0x00,0x01
[subject]補助装/_:d_list,0x2A0,YULST->YU_ma3,0x00,0x05,YULST->YU_ma4,offset
[back]
[subject]全スキルＭＡＸ化/実行/_:b_toggle,0x00,YULST->YU_ma5,offset
[back]
[/group]


[group]YU_PRmk
[subject]一般ステータス編集:dir
[subject]魂/現在値/固定:calc,0xE60,0x0000,0x270F,unsigned
[subject]ＬＶ/現在値/固定:calc,0xDC0,0x00,0x09,unsigned
[e_with],0x0000,0x03E7,unsigned
[subject]生命/現在値/固定:calc,0xDD0
[subject]物攻/現在値/固定:calc,0xDE0
[subject]ＣＬ攻/現在値/固定:calc,0xDF0
[subject]物防/現在値/固定:calc,0xE00
[subject]ＣＬ防/現在値/固定:calc,0xE10
[subject]経験/現在値/固定:calc,0xE20
[subject]判断/現在値/固定:calc,0xE30
[/e_with]
[subject]召喚/現在値/固定:calc,0xE40,0x00,0x63,unsigned
[subject]特防/現在値/固定:calc,0xE50,0x00,0x63,unsigned
[e_with],0x0000,0x03E7,unsigned
[subject]感情/現在値/固定:calc,0xE70
[subject]知能/現在値/固定:calc,0xE80
[subject]性感/現在値/固定:calc,0xE90
[subject]従属/現在値/固定:calc,0xEA0
[/e_with]
[back]
[subject]武装任意変更:dir
[subject]近接装/_:list,0x280,YULST->YU_mk1,0x00,0x01
[subject]遠距離/_:list,0x270,YULST->YU_mk2,0x00,0x01
[subject]防御装/_:list,0x230,YULST->YU_aa4,0x00,0x01
[subject]補助装/_:d_list,0x260,YULST->YU_mk3,0x00,0x05,YULST->YU_aa6,offset
[back]
[subject]全スキルＭＡＸ化/実行/_:b_toggle,0x00,YULST->YU_mk4,offset
[back]
[/group]


[group]YU_mk1
未装備
対装甲爆裂槍[G]
パルチザンの斧[無]
ユダの剣[R]
[/group]


[group]YU_mk2
未装備
Ｍ８リボルディング[無]
ハナブラムの矢[BR]
ＸＫ・１１マシンガン[無]
[/group]


[group]YU_mk3
未装備
昴[無]
死者の書[無]
呂型多弾ユニット
ＤＤＳ
[/group]


[group]YU_mk4
0x4C0,09000000
0x690,08000000
0x990,09000000
0x9A0,08000000
0x9B0,08000000
0x9C0,08000000
0x9D0,08000000
[/group]


[group]YU_CG
[subject]GRAPHICS:dir
	[subject]ＡＬＬ ＯＮ/実行/_:b_toggle,0x00,YULST->YU_CG1,offset
	[subject]ＡＬＬ ＯＦＦ/実行/_:b_toggle,0x00,YULST->YU_CG2,offset
[/group]


[group]YU_CG1
0x00E0,0x011F-02000000????????????????????????
0x06C0,0x06EF-01000000????????????????????????
0x1140,0x132F-01000000????????????????????????
[/group]


[group]YU_CG2
0x00E0,0x011F-00000000????????????????????????
0x06C0,0x06EF-00000000????????????????????????
0x1140,0x132F-00000000????????????????????????
[/group]


[group]YU_ma5
0x4B0,09000000
0x680,08000000
0x930,09000000
0x940,08000000
0x960,08000000
0x970,08000000
0x980,08000000
[/group]


[group]YU_aa1
0x660,07000000
0x6A0,08000000
0xA90,09000000
0xAA0,09000000
0xAB0,08000000
0xAC0,08000000
0xAD0,08000000
[/group]


[group]YU_ma1
未装備
対装甲爆裂槍[B]
トルメキアの歌声[Y]
ソドムの微笑み[無]
ミンキーミキサー[B]
ユダの剣[無]
[/group]


[group]YU_ma2
未装備
Ｍ８リボルディング[無]
ハート・キャッチャー[無]
ＸＫ・１１マシンガン[無]
[/group]


[group]YU_ma3
未装備
昴[無]
萩原[無]
ＤＤＳ
[/group]


[group]YU_ma4
,0x00=00000000
,0x00=01000000
,0x00=02000000
,0x00=05000000
[/group]


[group]YU_aa2
未装備
対装甲爆裂槍[G]
ソドムの微笑み[無]
[/group]


[group]YU_aa3
未装備
Ｍ８リボルディング[無]
もこもこ[BR]
フランソワーズ[BR]
ＸＫ・１１マシンガン[無]
[/group]


[group]YU_aa4
未装備
零式発生装置[無]
マラヒダエル[R]
アスモデル[Y]
アムビエル[B]
[/group]


[group]YU_aa5
未装備
昴[無]
戦は勝てる[無]
呂型多弾ユニット
ＤＤＳ
[/group]


[group]YU_aa6
,0x00=00000000
,0x00=01000000
,0x00=02000000
,0x00=04000000
,0x00=05000000
[/group]


[group]YU_nr2
未装備
対装甲爆裂槍[無]
パルチザンの斧[無]
ユダの剣[R]
[/group]


[group]YU_nr3
未装備
Ｍ８リボルディング[無]
スペルバスター[無]
ＸＫ－１１マシンガン[無]
[/group]


[group]YU_nr4
未装備
昴[無]
呂型多弾ユニット
ＤＤＳ
[/group]


[group]YU_nr5
,0x00=00000000
,0x00=01000000
,0x00=04000000
,0x00=05000000
[/group]


[group]YU_ya1
0x640,09000000
0x650,09000000
0x670,08000000
0x8E0,08000000
0x900,08000000
0x910,08000000
0x920,08000000
[/group]


[group]YU_ya2
未装備
対装甲爆裂槍[A]
ナギナタ[無]
トルメキアの歌声[Y]
[/group]


[group]YU_ya3
未装備
Ｍ８リボルディング[無]
ＸＫ－１１マシンガン[無]
[/group]


[group]YU_ya4
未装備
昴[無]
知恵の実
呂型多弾ユニット
ＤＤＳ
[/group]


[group]CH_a
未確定
赤木ゆり
相川茉莉子
木葉メイ
姉小路ありさ
なぎさ
[/group]


[group]CH_b
,0x00=00000000
,0x00=01000000
,0x00=03000000
,0x00=05000000
,0x00=07000000
,0x00=09000000
[/group]
